micronaut:
  application:
    name: springWithMnData

datasources:
  default:
    url: "jdbc:mysql://127.0.0.1:3307/books"
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: MYSQL

